#!/usr/bin/env python3
"""Generate ui_kits/certa-studio/kit.global.jsx from the canonical ESM source
(Primitives.jsx + components/*.jsx) so the click-through app consumes the REAL
DS 4.0 components (single source of truth) via the global-scope Babel loader.

Transforms applied: drop `import` lines, strip `export ` (default-export object
removed), and rewrite bare React hooks to React.<hook> (global React UMD).
"""
import os, re

CS = os.path.dirname(__file__)
# dependency order: Primitives first, then components (CountryDropdown before PhoneInput)
SOURCES = [
    "Primitives.jsx",
    "components/CountryDropdown.jsx",
    "components/PhoneInput.jsx",
    "components/FilterChip.jsx",
    "components/ReadOnlyField.jsx",
    "components/MaskedField.jsx",
]
HOOKS = ["useState", "useEffect", "useRef", "useMemo", "useCallback", "useId"]

def strip(src):
    out = []
    lines = src.splitlines()
    i = 0
    while i < len(lines):
        ln = lines[i]
        s = ln.strip()
        if s.startswith("import "):
            i += 1; continue
        if s.startswith("export default"):
            # skip until the line that closes the default export (`};` or `}`)
            while i < len(lines) and lines[i].strip() not in ("};", "}"):
                i += 1
            i += 1  # skip the closer too
            continue
        ln = re.sub(r"^(\s*)export\s+function\b", r"\1function", ln)
        ln = re.sub(r"^(\s*)export\s+const\b", r"\1const", ln)
        ln = re.sub(r"^(\s*)export\s+(\{)", r"\1// removed export \2", ln)
        out.append(ln)
        i += 1
    text = "\n".join(out)
    # bare hooks -> React.<hook> (not already member-accessed)
    for h in HOOKS:
        text = re.sub(r"(?<![.\w])" + h + r"\b", "React." + h, text)
    return text

parts = ["/* AUTO-GENERATED by build_kit.py — do not edit. Source of truth:",
         "   Primitives.jsx + components/*.jsx (canonical DS 4.0 kit). */",
         "/* global React */"]
for rel in SOURCES:
    p = os.path.join(CS, rel)
    parts.append(f"\n/* ===== {rel} ===== */")
    parts.append(strip(open(p).read()))
# expose to window for the global-scope screens/app
names = ["Button","Pagination","Table","Icon","Badge","Tag","ProcessStatus","Field","Input","IconButton",
         "Checkbox","CheckboxPill","MultiSelect","Card","SectionHeader","EmptyState",
         "ProgressSteps","Avatar","Toggle","Tabs","Alert","Switch","Dialog","RAGField",
         "KPIStatCard","Gauge","CircularProgress","SplitButton","TimeField","FileDropzone",
         "FilterChip","ReadOnlyField","MaskedField","CountryDropdown","PhoneInput",
         "SAMPLE_COUNTRIES","STATUS_COLOR"]
parts.append("\n/* expose canonical kit as globals for the app shell */")
parts.append("Object.assign(window, { " + ", ".join(names) + " });")

out_path = os.path.join(CS, "kit.global.jsx")
open(out_path, "w").write("\n".join(parts) + "\n")
print("wrote", out_path)
# sanity: confirm the real Checkbox SVG path made it in, and no import/export left
g = open(out_path).read()
print("has Checkbox SVG path:", "M3.5 8.5 L6.5 11.5 L12.5 5" in g)
print("residual 'export '/'import ':", len(re.findall(r"^\s*(export|import)\s", g, re.M)))
print("bare hook leaks:", len(re.findall(r"(?<![.\w])useState\b(?!\s*\})", g)) )
